on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32  # v5.0.2
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Test
        run: go test -mod=vendor ./...

  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Set up Docker
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db   # v3.6.1
      - name: Build
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85   # v6.7.0
        with:
          push: false
          tags: pdsync
